### ISSUE TITLE
Page on personal site

### ISSUE THREAD

**Issue by jmeaster30** [jmeaster30/vore#56]
I want people to be able to try out the language on my personal site so:

- [x] Build some basic page with info about the language
- [x] Get libvore to compile to WASM
- [x] Integrate libvore WASM into the page and build up a UI that is similar to [regexr](https://regexr.com/)

**Comment by jmeaster30** [comment]
I got it to compile to WASM!

**Comment by jmeaster30** [comment]
This is pretty much done just some polish left
